language: csharp
sudo: required
dist: trusty
mono: latest
dotnet: 2.0
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

branches:
  only:
    - master

solution: Vostok.Core.sln

install:
  - nuget restore Vostok.Core.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Vostok.Core.Tests/bin/Release/netcoreapp2.0/Vostok.Core.Tests.dll
