language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0.0
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

branches:
  only:
    - master

solution: Vostok.Core.sln

script:
  - cd Vostok.ClusterClient.Tests
  - dotnet build -c Release -f netcoreapp2.0
  - dotnet xunit
