version: '1.0.0-{build}'
branches:
  only:
    - master
image: Visual Studio 2017
install:
  - nuget restore
configuration: Debug
before_build:
  - ps: |
      $xmlPath = "$env:appveyor_build_folder\Core\Core.csproj"
      $xml = [xml](get-content $xmlPath)
      $propertyGroup = $xml.Project.PropertyGroup | Where { $_.Version}
      $propertyGroup.Version = $env:appveyor_build_version
      $xml.Save($xmlPath)
after_build: appveyor PushArtifact "Vostok.Core.$env:appveyor_build_version.nuget"
